function interf(Vin,f,R1,R2,E,tip,s1,s2);

Fig=figure('Name','Inversor cu AO',... %se creaza o noua figura
'Units','normalized',...
'NumberTitle','off',...
'Position',[0.1 0.1 0.8 0.8],...
'Color',[0.4 0.4 0.4]);


%MENU
meniu=uimenu('Label', 'DOCUMENTATION','foregroundcolor','r');

uimenu(meniu,'Label','Web Page','foregroundcolor','r',...
'Callback','open(''Spulber_Bogdan_GAC.htm'')');
uimenu(meniu,'Label','PPT-Presentation','foregroundcolor','r',...
'Callback','open(''Spulber_Bogdan_GAC.pptx'')');

%TEXT
Bt = uicontrol('Style','text',...
'Units','normalized',...
'Position',[0.11 0.9 0.2 0.05],...
'backgroundcolor',[0.7 0.7 0.7],...
'foregroundcolor','black',...
'String','Inversor cu AO',...
'fontsize',18)

%Poza Inversor  AO
picture=imread('AO_INVERSOR.png');
subplot('Position',[0.025 0.45 0.4 0.45]);
imshow(picture);

%----Grup butoane semnal intrare----%
Box1=uibuttongroup('Visible','on',...
'BackgroundColor',[0.7 0.7 0.7],...
'ForegroundColor','black',...
'Title','Semnal de intrare',...
'FontSize',12,...
'TitlePosition','centertop',...
'Tag','buttons',...
'Position',[0.1 0.1 0.2 0.35]);

%Selectare tip semnal
Tip_semnal=uicontrol('Style','popupmenu',...
    'Units','normalized',...
    'Position',[0.1 0.7 0.8 0.2],...
    'FontSize',12,...
    'String','Semnal sinusoidal|Semnal dreptunghiular|Semnal triunghiular',...
    'Value',tip,...
    'Parent',Box1,...
    'BackgroundColor','w',...
    'Callback','tip=get(gco,"value"),close,interf(Vin,f,R1,R2,E,tip,s1,s2)');

%Editare amplitudine semnal
Amplitudine_semnal=uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','w',...
'ForegroundColor','black',...
'Position',[0.1 0.6 0.5 0.1],...
'String','Amplitudine [V]',...
'FontSize',12,...
'Parent',Box1);

Edit_amplitudine=uicontrol('Style','edit',...
'Units','normalized',...
'BackgroundColor','w',...
'ForegroundColor','black',...
'Position',[0.65 0.6 0.3 0.1],...
'String',Vin,...
'FontSize',10,...
'Parent',Box1,...
'Callback','Vin=str2num(get(gco,''string'')),close;interf(Vin,f,R1,R2,E,tip,s1,s2);');

%Editare frecventa
Frecventa_semnal=uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','w',...
'ForegroundColor','black',...
'Position',[0.1 0.4 0.5 0.1],...
'String','f [Hz]',...
'FontSize',12,...
'Parent',Box1);

Edit_frecventa=uicontrol('Style','edit',...
'Units','normalized',...
'BackgroundColor','w',...
'ForegroundColor','black',...
'Position',[0.65 0.4 0.3 0.1],...
'String',f,...
'FontSize',10,...
'Parent',Box1,...
'Callback','f=str2num(get(gco,''string'')),close;interf(Vin,f,R1,R2,E,tip,s1,s2);');

%Alimentare diferentiala%
TEXT=uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor',[0.7 0.7 0.7],...
'ForegroundColor','black',...
'Position',[0.15 0.05 0.7 0.3],...
'String','Alimentare diferentiala',...
'FontSize',12,...
'Parent',Box1);

A_d_TEXT=uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','w',...
'ForegroundColor','black',...
'Position',[0.1 0.1 0.5 0.1],...
'String','+/- E [V]',...
'FontSize',12,...
'Parent',Box1);

A_d_EDIT=uicontrol('Style','edit',...
'Units','normalized',...
'BackgroundColor','w',...
'ForegroundColor','black',...
'Position',[0.65 0.1 0.3 0.1],...
'String',E,...
'FontSize',10,...
'Parent',Box1,...
'Callback','E=str2num(get(gco,''string'')),close;interf(Vin,f,R1,R2,E,tip,s1,s2);');

%-----Grup Butoane Rezistente-----%

Box2=uibuttongroup('Visible','on',...
'BackgroundColor',[0.7 0.7 0.7],...
'ForegroundColor','black',...
'Title','Rezistente',...
'FontSize',12,...
'TitlePosition','centertop',...
'Tag','buttons',...
'Position',[0.3 0.1 0.2 0.35]);

%Rezistenta 1
R1_text=uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','w',...
'ForegroundColor','black',...
'Position',[0.1 0.6 0.4 0.1],...
'String','R1 [Kohm]',...
'FontSize',12,...
'Parent',Box2);

Edit_R1=uicontrol('Style','edit',...
'Units','normalized',...
'BackgroundColor','w',...
'ForegroundColor','black',...
'Position',[0.6 0.6 0.3 0.1],...
'String',R1,...
'FontSize',10,...
'Parent',Box2,...
'Callback','R1=str2num(get(gco,''string'')),close;interf(Vin,f,R1,R2,E,tip,s1,s2);');

%Rezistena R2

R2_text=uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','w',...
'ForegroundColor','black',...
'Position',[0.1 0.4 0.4 0.1],...
'String','R2 [Kohm]',...
'FontSize',12,...
'Parent',Box2);

Edit_R2=uicontrol('Style','edit',...
'Units','normalized',...
'BackgroundColor','w',...
'ForegroundColor','black',...
'Position',[0.6 0.4 0.3 0.1],...
'String',R2,...
'FontSize',10,...
'Parent',Box2,...
'Callback','R2=str2num(get(gco,''string'')),close;interf(Vin,f,R1,R2,E,tip,s1,s2);');

%----Grup selectare semnale----%

Box3=uibuttongroup('Visible','on',...
'BackgroundColor',[0.7 0.7 0.7],...
'ForegroundColor','black',...
'Title','Semnale',...
'FontSize',12,...
'TitlePosition','centertop',...
'Tag','buttons',...
'Position',[0.499 0.251 0.2 0.2]);

check1=uicontrol('Style','checkbox',...
    'Units','normalized',...
    'Position',[0.4 0.5 0.2 0.2],...
    'FontSize',10,...
    'String','Vin',...
    'Value',s1,...
    'BackgroundColor','w',...
    'Parent',Box3,...
    'Callback','s1=get(gco,"Value"),close,interf(Vin,f,R1,R2,E,tip,s1,s2)');

check2=uicontrol('Style','checkbox',...
    'Units','normalized',...
    'Position',[0.4 0.3 0.2 0.2],...
    'FontSize',10,...
    'String','Vout',...
    'Value',s2,...
    'BackgroundColor','w',...
    'Parent',Box3,...
    'Callback','s2=get(gco,"Value"),close,interf(Vin,f,R1,R2,E,tip,s1,s2)');


%---------Amplificarea------%

Ampl=uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','w',...
'ForegroundColor','black',...
'Position',[0.5 0.2 0.1 0.05],...
'String','Amplificarea',...
'FontSize',12);

Ampl1=uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','w',...
'ForegroundColor','black',...
'Position',[0.6 0.2 0.1 0.05],...
'String',-R2/R1,...
'FontSize',12);

%-----Amplitudinea semnalului de iesire----%
Aout1=uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','w',...
'ForegroundColor','black',...
'Position',[0.5 0.15 0.1 0.05],...
'String','Amplitudine Vout',...
'FontSize',12);

Aout2=uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','w',...
'ForegroundColor','black',...
'Position',[0.6 0.15 0.1 0.05],...
'String',(-R2/R1)*Vin,...
'FontSize',12);


%--------Grup Erori -------%
Box5=uibuttongroup('Visible','on',...
'BackgroundColor',[0.7 0.7 0.7],...
'ForegroundColor','black',...
'Title','Atentiuni',...
'FontSize',12,...
'TitlePosition','centertop',...
'Tag','buttons',...
'Position',[0.69 0.1 0.2 0.35]);

Eroare1=uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','g',...
'ForegroundColor','black',...
'Position',[0.05 0.8 0.9 0.1],...
'String','Semnal de iesire normal',...
'FontSize',12,...
'Parent',Box5);

Eroare2=uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','g',...
'ForegroundColor','black',...
'Position',[0.05 0.6 0.9 0.1],...
'String','Frecventa in limite normale',...
'FontSize',12,...
'Parent',Box5);


Eroare3=uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','g',...
'ForegroundColor','black',...
'Position',[0.05 0.4 0.9 0.1],...
'String','Rezistente in limite normale',...
'FontSize',12,...
'Parent',Box5);

Eroare4=uicontrol('Style','text',...
'Units','normalized',...
'BackgroundColor','g',...
'ForegroundColor','black',...
'Position',[0.05 0.2 0.9 0.1],...
'String','Alimentare dif in limite normale',...
'FontSize',12,...
'Parent',Box5);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%ATENTIUNI%
Vout=(-R2/R1)*Vin;%amplitudinea semnalului de iesire
T=1/f; %perioada
VAR=Vout;

if -Vout>E 
    set(Eroare1,'string','Semnal de iesire "taiat"');
    set(Eroare1,'BackgroundColor','r');
    Vout=-E;
   set(Aout2,'string',Vout);
end

%(in cazul daca amplitudinea semnalului de iesire este negativa)
if Vout>E 
    set(Eroare1,'string','Semnal de iesire "taiat"');
    set(Eroare1,'BackgroundColor','r');
    Vout=E;
   set(Aout2,'string',Vout);
end

if f>100000000
    set(Eroare2,'string',"Frecventa prea mare!");
    set(Eroare2,'BackgroundColor','r');
    T=0;
end

if f<1
    set(Eroare2,'string',"Frecventa prea mica!");
    set(Eroare2,'BackgroundColor','r');
    T=0;
end
 
if R1<1 || R2<1 || R1>10000 || R2>10000
    set(Eroare3,'string',"Rezistente in limite anormale");
    set(Eroare3,'BackgroundColor','r');
    T=0;
end

if E<1 || E>1000000000
    set(Eroare4,'string',"+/- E in limite anormale");
    set(Eroare4,'BackgroundColor','r');
    T=0;
end

    
%--------Reprezentare semnale grafic------%

t=0:T/100:2*T; % alegem un interval de timp de reprezentare



subplot('position',[0.5 0.55 0.4 0.4]);%setam o fereastra de plotare
%SINUS
if tip==1
      
vi=Vin*sin(2*pi*f*t); % semnal de intrare
vout=VAR*sin(2*pi*f*t);

for i=1:length(t)
    if vout(i)>E
        vout(i)=E
    elseif vout(i)<-E
        vout(i)=-E
    end
end

p1=plot(t,vi,'color','b');
hold on;
p2=plot(t,vout,'color','r');
grid on;
title('Semnale');
xlabel('Timp [s]');
ylabel('Amplitudine [V]');




if s1==0
    set(p1,'visible','off');
end

if s2==0
    set(p2,'visible','off');
end

end

%DREPTUNGHI
if tip==2
      
vi=Vin*sign(sin(2*pi*f*t)); % semnal de intrare
vout=Vout*sign(sin(2*pi*f*t));

for i=1:length(t)
    if vout(i)>E
        vout(i)=E
    elseif vout(i)<-E
        vout(i)=-E
    end
end

p1=plot(t,vi,'color','b');
hold on;
p2=plot(t,vout,'color','r');
grid on;
title('Semnale');
xlabel('Timp [s]');
ylabel('Amplitudine [V]');

if s1==0
    set(p1,'visible','off');
end

if s2==0
    set(p2,'visible','off');
end

end

%TRIUNGHI
if tip==3
      
vi=Vin*2/3*(asin(sin(2*pi*f*t))); % semnal de intrare
vout=Vout*2/3*(asin(sin(2*pi*f*t)));
p1=plot(t,vi,'color','b');
hold on;
p2=plot(t,vout,'color','r');
grid on;
title('Semnale');
xlabel('Timp [s]');
ylabel('Amplitudine [V]');

if s1==0
    set(p1,'visible','off');
end

if s2==0
    set(p2,'visible','off');
end


end



legend('v in','v out');